export const envirData = [
  {
    id: 8,
    communityText:
      "딩🔔🔔🔔 🔔🔔딩🔔🔔딩🔔🔔🔔🔊🌞👍🔊 빠빠빠😄- 빠-? 빠 ?빠빠빠빠?‼- 🌝굿모닝🌞 빠빠빠 🕒🕞🕓🕗🕖빠 빠 🕘🕗🕚🕥🕦빠빠🕖🕢🕚🕥🕞빠빠 굿모닝💮🎉📞📣빠빠빠 빠 🕗🕞🕞빠 🕖🕢🕟🕓빠🕖🕖🕗빠빠 뷰티풀↗📣데이 ?~~~빠빠빠 빠 잇쳐 ?뷰티풀📣🌈데이🌌‼‼?⁉ 딩🔔🔔🔔 🔔🔔딩🔔🔔딩🔔🔔🔔🔊🌞👍🔊 빠빠빠😄- 빠-? 빠 ?빠빠빠빠?‼- 🌝굿모닝🌞 빠빠빠 🕒🕞🕓🕗🕖빠 빠 🕘🕗🕚🕥🕦빠빠🕖🕢🕚🕥🕞빠빠 굿모닝💮🎉📞📣빠빠빠 빠 🕗🕞🕞빠 🕖🕢🕟",
    date: "2023-11-13T12:48:55.464894",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "환경",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "false",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "false",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "true",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "true",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "true",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "true",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "true",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 7,
    communityText:
      "죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘! 😘 이쁘게 봐줘잉~ 😍 돌아와줘! ❣️ 사랑해줘~~ 🎤🎶🎶🎵 죄송한 마음을 담아 ❤️ 작곡 작사를 해 보았어요 💕 정말 죄송합니다 😉 예쁘게 들어 주세요 💖 쏘리 쏘리 암 쏘리 🎵 내가 미안해 🎙🎙 한번만 봐줘!",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "true",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
];

export const EduData = [
  {
    id: 7,
    communityText: "이야기",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "교육",
    subject: "교육어쩌구",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "false",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 2,
    communityText: "이야기",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "교육",
    subject: "교육어쩌구",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "false",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
  {
    id: 5,
    communityText: "이야기",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "교육",
    subject: "교육어쩌구",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
    likeStatus: "false",
    quotText: "asidjfaiejfaidjfiajeifj",
  },
];
