export const PopularCommunityData = [
  {
    id: 6,
    communityText: "이야기",
    date: "2023-11-13T12:20:04.347316",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "노량진",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
  },
  {
    id: 7,
    communityText: "이야기",
    date: "2023-11-13T12:20:59.176275",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "하이",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
  },
  {
    id: 8,
    communityText: "이야기",
    date: "2023-11-13T12:48:55.464894",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "환경",
    likeCount: 1,
    commentCount: 0,
    contentsId: 3,
    contents: null,
  },
  {
    id: 2,
    communityText: "이야기",
    date: "2023-11-13T01:43:19.359643",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "오염",
    likeCount: 0,
    commentCount: 0,
    contentsId: 1,
    contents: null,
  },
  {
    id: 3,
    communityText: "이야기",
    date: "2023-11-13T01:43:29.678513",
    writerId: "LOCAL-2341",
    nickname: "nkcikname",
    profileImg: "profile",
    area: "환경",
    subject: "후쿠시마 오염수",
    keyword: "환경",
    likeCount: 0,
    commentCount: 0,
    contentsId: 1,
    contents: null,
  },
];
